version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: my-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: my-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongo:27017/lmsDatabase
      - JWT_SECRET=supersecret
    depends_on:
      - mongo
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: pnpm run dev

  frontend:
    build: ./frontend
    container_name: my-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: pnpm run dev

volumes:
  mongo_data:
